-- Customer Data Insights (SQL + Python + Power BI)
CREATE DATABASE customer_Trend;

use customer_Trend;
-- --Q1. What is the total revenue generated by male vs. female customers?
SELECT gender, SUM(purchase) as Total_Revenue
FROM Trend
group by  gender ;

-- Which customers used a discount but still spent more than the average purchase amount? 
select purchase , discount_applied 
from trend 
where discount_applied = 'yes ' and purchase >= (select avg(purchase) from trend );
 
--  Q3. Which are the top 5 products with the highest average review rating?
select item_purchased , round(avg(review_rating),2) as rating
from trend 
group by item_purchased
order by avg(review_rating) desc 
limit 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select  shipping_type, round (avg(purchase),2) as total
from trend 
where shipping_type in ('standard' ,'express')
group by shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue 
-- --between subscribers and non-subscribers.
select subscription_status,
count(customer_id) as customer ,
 round(avg(purchase),2) as total,
 round(sum(purchase),2) as Reveneu 
from trend 
group by subscription_status
order by total , Reveneu desc;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased , 
round(100 * sum(case when discount_applied = 'yes'then 1 else 0 end )/count(*),2)as discount
from trend 
 Group by item_Purchased 
order by discount desc
limit 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 

with Customer_type as 
	(select customer_id,
    case 
    when previous_purchases = 1 then 'New'
    when previous_purchases between 2 and 10 then 'Returning'
    else 'Loyal'
end as segment
from trend )
    
Select segment, count(*) as customer
from Customer_type
group by segment;



    





